-- Brand owner notification settings (SMS quota + LINE toggles)
ALTER TABLE "Brand" ADD COLUMN IF NOT EXISTS "smsQuotaGranted" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Brand" ADD COLUMN IF NOT EXISTS "lineNotifyNewOrder" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Brand" ADD COLUMN IF NOT EXISTS "lineNotifySkewerOrder" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Brand" ADD COLUMN IF NOT EXISTS "lineNotifyDailySummary" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "alertSmsPhone" TEXT;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "smsNotifyNewOrder" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Branch" ADD COLUMN IF NOT EXISTS "smsNotifySkewerOrder" BOOLEAN NOT NULL DEFAULT false;

ALTER TYPE "SmsSendPurpose" ADD VALUE IF NOT EXISTS 'BRAND_ALERT_NEW_ORDER';
ALTER TYPE "SmsSendPurpose" ADD VALUE IF NOT EXISTS 'BRAND_ALERT_SKEWER_ORDER';
